[package]
name = "pointer-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pointer-core"
path = "src/main.rs"

[dependencies]
platform = { path = "../platform" }
serde = { workspace = true }
serde_json = { workspace = true }
wcore = { package = "core", path = "../core" }
api = { path = "../api" }
base64 = { workspace = true }
